export const COUNT_CART = "COUNT_CART";
export const GET_CART_DATA = "GET_CART_DATA";
export const GET_ADDRESS = "GET_ADDRESS";
export const GET_TOTALAMOUNT = "GET_TOTALAMOUNT";
export const GET_ALREADYAPPLIED = "GET_ALREADYAPPLIED";
export const GET_SHIPPINGCOST = 'GET_SHIPPINGCOST';